// Game data for all categories
const gameData = {    friends: [
        { name: 'Aslan', image: 'images/friends/aslan2.jpg' },
        { name: 'Ayan', image: 'images/friends/ayan.jpeg' },
        { name: 'Cosqun', image: 'images/friends/cosqun.jpeg' },
        { name: 'Fexriyye', image: 'images/friends/fexriye.jpeg' },
        { name: 'Ismayil', image: 'images/friends/ismayil.jpeg' },
        { name: 'Kaan', image: 'images/friends/kaan.jpeg' },
        { name: 'Mutalib', image: 'images/friends/mutalib.jpeg' },
        { name: 'Nihad', image: 'images/friends/nihad.jpeg' },
        { name: 'Onur', image: 'images/friends/onur.jpeg' },
        { name: 'Razil', image: 'images/friends/razil.jpeg' },
        { name: 'Rehim', image: 'images/friends/Rehim.jpeg' },
        { name: 'Sema', image: 'images/friends/sema.jpeg' },
        { name: 'Sukufe', image: 'images/friends/sukufe.jpeg' },
        { name: 'Tebriz', image: 'images/friends/tebriz.jpeg' },
        { name: 'Zulfiyye', image: 'images/friends/zulfiye.jpeg' },
        { name: 'Seyfi', image: 'images/friends/seyfi.jpeg' },
        { name: 'Abbas', image: 'images/friends/abbas.jpg' },
        { name: 'Ayaz', image: 'images/friends/ayaz.jpg' },
        { name: 'Diana', image: 'images/friends/diana.jpg' },
        { name: 'Huseyn', image: 'images/friends/huseyn.jpg' },
        { name: 'Elnare', image: 'images/friends/elnare.jpg' },
        { name: 'Fidan', image: 'images/friends/fidan2.jpg' },
        { name: 'Isa', image: 'images/friends/isa.jpg' },        { name: 'Islam', image: 'images/friends/islam.jpg' },
        { name: 'Kamran', image: 'images/friends/kamran2.jpg' },
        { name: 'Prabesh', image: 'images/friends/prabesh.jpg' },
        { name: 'Sebuhi', image: 'images/friends/sebuhi.jpg' }
    ],    teachers: [
        { name: 'Davud', image: 'images/teachers/davud.jpeg' },
        { name: 'Efsane', image: 'images/teachers/efsane.jpeg' },
        { name: 'Etibar', image: 'images/teachers/etibar.jpeg' },
        { name: 'Hamed', image: 'images/teachers/hamed.jpeg' },
        { name: 'Hicran', image: 'images/teachers/hicran.jpeg' },
        { name: 'Husniyye', image: 'images/teachers/husniye.jpeg' },
        { name: 'Mirramin', image: 'images/teachers/mirramin.jpeg' },
        { name: 'Nurlana', image: 'images/teachers/nurlana.jpeg' },
        { name: 'Qacay', image: 'images/teachers/qacay.jpeg' },
        { name: 'Qedir', image: 'images/teachers/qedir.jpeg' },
        { name: 'Rasim', image: 'images/teachers/rasim.jpeg' },
        { name: 'Rehman', image: 'images/teachers/rehman.jpeg' },
        { name: 'Suheyla', image: 'images/teachers/suheyla.jpeg' },
        { name: 'Vuqar', image: 'images/teachers/vuqar.png' },
        { name: 'Xeyale', image: 'images/teachers/xeyale.jpeg' },
        { name: 'Esmer', image: 'images/teachers/esmer.jpg' }
    ],countries: [
        { name: 'Turkey', image: 'images/countries/turkey.jpg' },
        { name: 'United States', image: 'images/countries/unitedstates.jpg' },
        { name: 'Germany', image: 'images/countries/germany.jpg' },
        { name: 'France', image: 'images/countries/france.jpg' },
        { name: 'Italy', image: 'images/countries/italy.jpg' },
        { name: 'Spain', image: 'images/countries/spain.jpg' },
        { name: 'United Kingdom', image: 'images/countries/unitedkingdom.jpg' },
        { name: 'Japan', image: 'images/countries/japan.jpg' },
        { name: 'Brazil', image: 'images/countries/brazil.jpg' },
        { name: 'Canada', image: 'images/countries/canada.jpg' },
        { name: 'Australia', image: 'images/countries/australia.jpg' },
        { name: 'Netherlands', image: 'images/countries/netherlands.jpg' },
        { name: 'Russia', image: 'images/countries/russia.jpg' },
        { name: 'India', image: 'images/countries/india.jpg' },
        { name: 'Argentina', image: 'images/countries/argentina.jpg' },
        { name: 'Norway', image: 'images/countries/norway.jpg' }
    ],    movies: [
        { name: 'The Shawshank Redemption', image: 'images/movies/shawshank.jpg' },
        { name: 'The Godfather', image: 'images/movies/godfather.jpg' },
        { name: 'Fight Club', image: 'images/movies/fightclub.jpg' },
        { name: 'The Prestige', image: 'images/movies/prestige.jpg' },
        { name: 'Forrest Gump', image: 'images/movies/forrest.jpg' },
        { name: 'Inception', image: 'images/movies/inception.jpg' },
        { name: 'The Matrix', image: 'images/movies/matrix.jpg' },
        { name: 'Interstellar', image: 'images/movies/interstellar.jpg' },
        { name: 'Titanic', image: 'images/movies/titanic.jpg' },
        { name: 'Avatar', image: 'images/movies/avatar.jpg' },
        { name: 'Shutter Island', image: 'images/movies/shutter.jpg' },
        { name: 'Se7en', image: 'images/movies/seven.jpg' },
        { name: 'The Pianist', image: 'images/movies/pianist.jpg' },
        { name: 'Scarface', image: 'images/movies/scarface.jpg' },
        { name: 'V for Vendetta', image: 'images/movies/vendetta.jpg' },
        { name: 'Schindler\'s List', image: 'images/movies/list.jpg' }
    ],    books: [
        { name: 'The Little Prince', image: 'images/books/prince.jpg' },
        { name: '1984', image: 'images/books/1984.jpg' },
        { name: 'Pride and Prejudice', image: 'images/books/pride.jpg' },
        { name: 'War and Peace', image: 'images/books/peace.jpg' },
        { name: 'Anna Karenina', image: 'images/books/anna.jpg' },
        { name: 'Martin Eden', image: 'images/books/martin.jpg' },
        { name: 'Kurk Mantolu Madonna', image: 'images/books/madonna.jpg' },
        { name: 'Ag zambaqlar olkesi', image: 'images/books/finland.jpg' },
        { name: 'The Kite Runner', image: 'images/books/kite.jpg' },
        { name: 'The Da Vinci Code', image: 'images/books/code.jpg' },
        { name: 'Mice and Man', image: 'images/books/mice.jpg' },
        { name: 'Seker Portakali', image: 'images/books/seker.jpg' },
        { name: 'Iki sehrin hikayesi', image: 'images/books/taleofcities.jpg' },
        { name: 'Rich dad Poor dad', image: 'images/books/rich.jpg' },
        { name: 'Atomic Habits', image: 'images/books/atomic.jpg' },
        { name: 'Qumarbaz', image: 'images/books/qumar.jpg' }
    ],    'football-players': [
        { name: 'Lionel Messi', image: 'images/football-players/messi.jpg' },
        { name: 'Cristiano Ronaldo', image: 'images/football-players/ronaldo.jpg' },
        { name: 'Neymar Jr', image: 'images/football-players/neymar.jpg' },
        { name: 'Kylian Mbappé', image: 'images/football-players/mbappe.jpg' },
        { name: 'Erling Haaland', image: 'images/football-players/haland.jpg' },
        { name: 'Lamine Yamal', image: 'images/football-players/yamal.jpg' },
        { name: 'Robert Lewandowski', image: 'images/football-players/leva.jpg' },
        { name: 'Vinisius Jr', image: 'images/football-players/vini.jpg' },
        { name: 'Desire Doue', image: 'images/football-players/doue.jpg' },
        { name: 'Pedri', image: 'images/football-players/pedri.jpg' },
        { name: 'Ousmane Dembele', image: 'images/football-players/dembele.jpg' },
        { name: 'Arda Guler', image: 'images/football-players/arda.jpg' },
        { name: 'Raphinha', image: 'images/football-players/raphinha.jpg' },
        { name: 'Bellingham', image: 'images/football-players/beling.jpg' },
        { name: 'Kevin De Bruyne', image: 'images/football-players/bruyne.jpg' },
        { name: 'Declan Rice', image: 'images/football-players/rice.jpg' }
    ],    'football-clubs': [
        { name: 'FC Barcelona', image: 'images/football-clubs/barca.jpg' },
        { name: 'Real Madrid', image: 'images/football-clubs/real.jpg' },
        { name: 'Manchester United', image: 'images/football-clubs/united.jpg' },
        { name: 'Manchester City', image: 'images/football-clubs/city.jpg' },
        { name: 'Liverpool', image: 'images/football-clubs/liverpul.jpg' },
        { name: 'Chelsea', image: 'images/football-clubs/celsi.jpg' },
        { name: 'Arsenal', image: 'images/football-clubs/arsenal.jpg' },
        { name: 'Tottenham', image: 'images/football-clubs/tottenham.jpg' },
        { name: 'Bayern Munich', image: 'images/football-clubs/bayern.jpg' },
        { name: 'Paris Saint-Germain', image: 'images/football-clubs/psg.jpg' },
        { name: 'Juventus', image: 'images/football-clubs/yuve.jpg' },
        { name: 'AC Milan', image: 'images/football-clubs/milan.jpg' },
        { name: 'Inter Milan', image: 'images/football-clubs/inter.jpg' },
        { name: 'Borussia Dortmund', image: 'images/football-clubs/dortmund.jpg' },        { name: 'Atletico Madrid', image: 'images/football-clubs/madrid.jpg' },
        { name: 'FC Porto', image: 'images/football-clubs/porto.jpg' }
    ],
    fruits: [
        { name: 'Apple', image: 'images/fruits/apple.jpg' },
        { name: 'Banana', image: 'images/fruits/banan.jpg' },
        { name: 'Orange', image: 'images/fruits/orange.jpg' },
        { name: 'Strawberry', image: 'images/fruits/straw.jpg' },
        { name: 'Grapes', image: 'images/fruits/grapes.jpg' },
        { name: 'Pineapple', image: 'images/fruits/pine.jpg' },
        { name: 'Watermelon', image: 'images/fruits/water.jpg' },
        { name: 'Mango', image: 'images/fruits/mango.jpg' },
        { name: 'Peach', image: 'images/fruits/peach.jpg' },
        { name: 'Cherry', image: 'images/fruits/cherry.jpg' },
        { name: 'Kiwi', image: 'images/fruits/kiwi.jpg' },
        { name: 'Avocado', image: 'images/fruits/avocado.jpg' },
        { name: 'Coconut', image: 'images/fruits/coconut.jpg' },
        { name: 'Pomegranate', image: 'images/fruits/granat.jpg' },
        { name: 'Blueberry', image: 'images/fruits/blue.jpg' },
        { name: 'Lemon', image: 'images/fruits/lemon.jpg' }
    ],
    songs: [
        { name: 'Hadise - Prenses', image: 'images/songs/hadise.jpg' },
        { name: 'Gülden Karaböcek - Sen Evlisin', image: 'images/songs/senevlisin.jpg' },
        { name: 'Sezen Aksu - Firuze', image: 'images/songs/firuze.jpg' },
        { name: 'Sagopa Kajmer - Ahmak Islatan', image: 'images/songs/sago.jpg' },
        { name: 'Kərim - Günahkar Mavi Xəzərdir', image: 'images/songs/kerim.jpg' },
        { name: 'Derya Uluğ - Sana Çıkıyor Yollar', image: 'images/songs/derya.jpg' },
        { name: 'Indila - Love Story', image: 'images/songs/indila.jpg' },
        { name: 'Billie Eilish, Khalid - lovely', image: 'images/songs/lovely.jpg' },
        { name: 'Tom Odell - Another Love', image: 'images/songs/another.jpg' },
        { name: 'Mavi Işıklar - Ankara Rüzgarı', image: 'images/songs/ankara.jpg' },
        { name: 'Röya — Bahar', image: 'images/songs/bahar.jpg' },
        { name: 'Duman - Yürek', image: 'images/songs/yurek.jpg' },
        { name: 'Madrigal - Seni Dert Etmeler', image: 'images/songs/madrigal.jpg' },
        { name: 'Elmira Rəhimova - Vefadarim Menim', image: 'images/songs/vefadarim.jpg' },        { name: 'Bella Ciao', image: 'images/songs/bella.jpg' },
        { name: 'Rauf Faik - детство', image: 'images/songs/detstvo.jpg' }
    ],
    universities: [
        { name: 'BMU', image: 'images/universities/bmu.jpg' },
        { name: 'BANM', image: 'images/universities/banm.jpg' },
        { name: 'ADA', image: 'images/universities/ada.jpg' },
        { name: 'ADNSU', image: 'images/universities/adnsu.jpg' },
        { name: 'UNEC', image: 'images/universities/unec.jpg' },
        { name: 'AZTU', image: 'images/universities/aztu.jpg' },
        { name: 'Xəzər', image: 'images/universities/xezer.jpg' },
        { name: 'BDU', image: 'images/universities/bdu.jpg' },
        { name: 'AZMIU', image: 'images/universities/azmiu.jpg' },
        { name: 'ADPU', image: 'images/universities/adpu.jpg' },
        { name: 'BSU', image: 'images/universities/bsu.jpg' },
        { name: 'ADU', image: 'images/universities/adu.jpg' },
        { name: 'MAA', image: 'images/universities/maa.jpg' },
        { name: 'ADDA', image: 'images/universities/adda.jpg' },
        { name: 'DIA', image: 'images/universities/dia.jpg' },
        { name: 'BQU', image: 'images/universities/bqu.jpg' }
    ],
    cities: [
        { name: 'Sumqayit', image: 'images/cities/sumqayit.jpg' },
        { name: 'Lacin', image: 'images/cities/lacin.jpg' },
        { name: 'Zerdab', image: 'images/cities/zerdab.jpg' },
        { name: 'Naxcivan', image: 'images/cities/naxcivan.jpg' },
        { name: 'Siyezen', image: 'images/cities/siyezen.jpg' },
        { name: 'Goranboy', image: 'images/cities/goran.jpg' },
        { name: 'Masalli', image: 'images/cities/masalli.jpg' },
        { name: 'Goycay', image: 'images/cities/goycay.jpg' },
        { name: 'Tovuz', image: 'images/cities/tovuz.jpg' },
        { name: 'Qusar', image: 'images/cities/qusar.jpg' },
        { name: 'Lenkeran', image: 'images/cities/lenkeran.jpg' },
        { name: 'Qazax', image: 'images/cities/qazax.jpg' },
        { name: 'Seki', image: 'images/cities/seki.jpg' },
        { name: 'Semkir', image: 'images/cities/semkir.jpg' },
        { name: 'Qebele', image: 'images/cities/qebele.jpg' },
        { name: 'Qax', image: 'images/cities/qax.jpg' }
    ],
    animals: [
        { name: 'Lion', image: 'images/animals/lion.jpg' },
        { name: 'Tiger', image: 'images/animals/tiger.jpg' },
        { name: 'Elephant', image: 'images/animals/elephant.jpg' },
        { name: 'Giraffe', image: 'images/animals/giraffe.jpg' },
        { name: 'Panda', image: 'images/animals/panda.jpg' },
        { name: 'Wolf', image: 'images/animals/wolf.jpg' },
        { name: 'Eagle', image: 'images/animals/eagle.jpg' },
        { name: 'Dolphin', image: 'images/animals/dolphin.jpg' },
        { name: 'Penguin', image: 'images/animals/penguin.jpg' },
        { name: 'Koala', image: 'images/animals/koala.jpg' },
        { name: 'Cheetah', image: 'images/animals/cheetah.jpg' },
        { name: 'Polar Bear', image: 'images/animals/bear.jpg' },
        { name: 'Kangaroo', image: 'images/animals/kenquru.jpg' },
        { name: 'Zebra', image: 'images/animals/zebra.jpg' },
        { name: 'Gorilla', image: 'images/animals/gorilla.jpg' },
        { name: 'Fox', image: 'images/animals/fox.jpg' }
    ],
    cars: [
        { name: 'Ferrari', image: 'images/cars/ferrari.jpg' },
        { name: 'Lamborghini', image: 'images/cars/lamborghini.jpg' },
        { name: 'Porsche', image: 'images/cars/porsche.jpg' },
        { name: 'BMW', image: 'images/cars/bmw.jpg' },
        { name: 'Mercedes-Benz', image: 'images/cars/mercedes.avif' },
        { name: 'Audi', image: 'images/cars/audi.jpg' },
        { name: 'Tesla', image: 'images/cars/tesla.jpg' },
        { name: 'Toyota Prado', image: 'images/cars/prado.jpg' },
        { name: 'Bugatti', image: 'images/cars/bugatti.jpg' },
        { name: 'Rolls-Royce', image: 'images/cars/rollsroyce.jpg' },
        { name: 'Bentley', image: 'images/cars/bentley.jpg' },
        { name: 'Niva', image: 'images/cars/niva.jpg' },
        { name: 'Maserati', image: 'images/cars/maserati.jpg' },
        { name: 'Jaguar', image: 'images/cars/jaguar.jpg' },
        { name: 'Range Rover', image: 'images/cars/rangerover.jpg' },
        { name: 'VAZ 2106', image: 'images/cars/06.jpg' }
    ],
    games: [
        { name: 'Dream League Soccer', image: 'images/games/dream.jpg' },
        { name: 'GTA V', image: 'images/games/gtav.jpg' },
        { name: 'eFootball', image: 'images/games/pes.jpg' },
        { name: 'Minecraft', image: 'images/games/minecraft.jpg' },
        { name: 'Hay Day', image: 'images/games/hayday.jpg' },
        { name: 'Call of Duty', image: 'images/games/cod.jpg' },
        { name: 'FIFA 24', image: 'images/games/fifa.jpg' },
        { name: 'SEKA', image: 'images/games/seka.jpg' },
        { name: 'Subway Surfers', image: 'images/games/subway.jpg' },
        { name: 'UNO', image: 'images/games/uno.jpg' },
        { name: 'Counter-Strike', image: 'images/games/cs.jpg' },
        { name: 'OSM', image: 'images/games/osm.jpg' },
        { name: 'Clash of Clans', image: 'images/games/clash.jpg' },
        { name: 'Among Us', image: 'images/games/amongus.jpg' },
        { name: 'Angry Birds', image: 'images/games/angry.jpg' },
        { name: 'Barbie', image: 'images/games/barbie.jpg' }
    ],
    food: [
        { name: 'Pizza', image: 'images/food/pizza.jpg' },
        { name: 'Burger', image: 'images/food/burger.jpg' },
        { name: 'Sushi', image: 'images/food/sushi.jpg' },
        { name: 'Pasta', image: 'images/food/pasta.jpg' },
        { name: 'Dolma', image: 'images/food/dolma.jpg' },
        { name: 'Plov', image: 'images/food/plov.jpg' },
        { name: 'Steak', image: 'images/food/steak.jpg' },
        { name: 'Ice Cream', image: 'images/food/icecream.jpg' },
        { name: 'Chocolate', image: 'images/food/chocolate.jpg' },
        { name: 'Shawarma', image: 'images/food/shawarma.jpg' },
        { name: 'Kebab', image: 'images/food/kebab.jpg' },
        { name: 'Qovurma', image: 'images/food/qovurma.jpg' },
        { name: 'Fish', image: 'images/food/fish.jpg' },
        { name: 'Croissant', image: 'images/food/croissant.jpg' },
        { name: 'Cake', image: 'images/food/cake.jpg' },
        { name: 'Donuts', image: 'images/food/donut.jpg' }
    ],
    'programming-languages': [
        { name: 'JavaScript', image: 'images/programming-languages/javascript.jpg' },
        { name: 'Python', image: 'images/programming-languages/python.jpg' },
        { name: 'Java', image: 'images/programming-languages/java.jpg' },
        { name: 'C++', image: 'images/programming-languages/cpp.jpg' },
        { name: 'C#', image: 'images/programming-languages/csharp.jpg' },
        { name: 'React Native', image: 'images/programming-languages/react.jpg' },
        { name: 'Go', image: 'images/programming-languages/go.jpg' },
        { name: 'Rust', image: 'images/programming-languages/rust.jpg' },
        { name: 'Swift', image: 'images/programming-languages/swift.jpg' },
        { name: 'Kotlin', image: 'images/programming-languages/kotlin.jpg' },
        { name: 'PHP', image: 'images/programming-languages/php.jpg' },
        { name: 'Ruby', image: 'images/programming-languages/ruby.jpg' },
        { name: 'C', image: 'images/programming-languages/c.jpg' },
        { name: 'Flutter', image: 'images/programming-languages/flutter.jpg' },        { name: 'SQL', image: 'images/programming-languages/sql.jpg' },
        { name: 'Dart', image: 'images/programming-languages/dart.jpg' }
    ],    'beautiful-women': [
        { name: 'Emma Watson', image: 'images/beautiful-women/emma-watson.svg' },
        { name: 'Scarlett Johansson', image: 'images/beautiful-women/scarlett-johansson.svg' },
        { name: 'Gal Gadot', image: 'images/beautiful-women/gal-gadot.svg' },
        { name: 'Margot Robbie', image: 'images/beautiful-women/margot-robbie.svg' },
        { name: 'Jennifer Lawrence', image: 'images/beautiful-women/jennifer-lawrence.svg' },
        { name: 'Angelina Jolie', image: 'images/beautiful-women/angelina-jolie.svg' },
        { name: 'Charlize Theron', image: 'images/beautiful-women/charlize-theron.svg' },
        { name: 'Natalie Portman', image: 'images/beautiful-women/natalie-portman.svg' },
        { name: 'Anne Hathaway', image: 'images/beautiful-women/anne-hathaway.svg' },
        { name: 'Emma Stone', image: 'images/beautiful-women/emma-stone.svg' },
        { name: 'Blake Lively', image: 'images/beautiful-women/blake-lively.svg' },
        { name: 'Mila Kunis', image: 'images/beautiful-women/mila-kunis.svg' },
        { name: 'Jessica Alba', image: 'images/beautiful-women/jessica-alba.svg' },
        { name: 'Megan Fox', image: 'images/beautiful-women/megan-fox.svg' },
        { name: 'Keira Knightley', image: 'images/beautiful-women/keira-knightley.svg' },
        { name: 'Rachel McAdams', image: 'images/beautiful-women/rachel-mcadams.svg' },
        { name: 'Zendaya', image: 'images/beautiful-women/zendaya.svg' },
        { name: 'Taylor Swift', image: 'images/beautiful-women/taylor-swift.svg' },
        { name: 'Ariana Grande', image: 'images/beautiful-women/ariana-grande.svg' },
        { name: 'Selena Gomez', image: 'images/beautiful-women/selena-gomez.svg' },
        { name: 'Bella Hadid', image: 'images/beautiful-women/bella-hadid.svg' },
        { name: 'Gigi Hadid', image: 'images/beautiful-women/gigi-hadid.svg' },
        { name: 'Kendall Jenner', image: 'images/beautiful-women/kendall-jenner.svg' },
        { name: 'Hailey Bieber', image: 'images/beautiful-women/hailey-bieber.svg' },
        { name: 'Emily Ratajkowski', image: 'images/beautiful-women/emily-ratajkowski.svg' },
        { name: 'Adriana Lima', image: 'images/beautiful-women/adriana-lima.svg' },
        { name: 'Candice Swanepoel', image: 'images/beautiful-women/candice-swanepoel.svg' },
        { name: 'Miranda Kerr', image: 'images/beautiful-women/miranda-kerr.svg' },
        { name: 'Karlie Kloss', image: 'images/beautiful-women/karlie-kloss.svg' },
        { name: 'Rosie Huntington', image: 'images/beautiful-women/rosie-huntington.svg' },
        { name: 'Irina Shayk', image: 'images/beautiful-women/irina-shayk.svg' },
        { name: 'Dua Lipa', image: 'images/beautiful-women/dua-lipa.svg' },
        { name: 'Rihanna', image: 'images/beautiful-women/rihanna.svg' },
        { name: 'Beyoncé', image: 'images/beautiful-women/beyonce.svg' },
        { name: 'Jennifer Lopez', image: 'images/beautiful-women/jennifer-lopez.svg' },
        { name: 'Priyanka Chopra', image: 'images/beautiful-women/priyanka-chopra.svg' },
        { name: 'Deepika Padukone', image: 'images/beautiful-women/deepika-padukone.svg' },
        { name: 'Aishwarya Rai', image: 'images/beautiful-women/aishwarya-rai.svg' },
        { name: 'Freida Pinto', image: 'images/beautiful-women/freida-pinto.svg' },
        { name: 'Lupita Nyongo', image: 'images/beautiful-women/lupita-nyongo.svg' },
        { name: 'Zoe Saldana', image: 'images/beautiful-women/zoe-saldana.svg' },
        { name: 'Thandie Newton', image: 'images/beautiful-women/thandie-newton.svg' },
        { name: 'Halle Berry', image: 'images/beautiful-women/halle-berry.svg' },
        { name: 'Monica Bellucci', image: 'images/beautiful-women/monica-bellucci.svg' },
        { name: 'Penelope Cruz', image: 'images/beautiful-women/penelope-cruz.svg' },
        { name: 'Salma Hayek', image: 'images/beautiful-women/salma-hayek.svg' },
        { name: 'Fan Bingbing', image: 'images/beautiful-women/fan-bingbing.svg' },
        { name: 'Liu Yifei', image: 'images/beautiful-women/liu-yifei.svg' }
    ]
};

// Get random items from array
function getRandomItems(array, count) {
    const shuffled = [...array].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, count);
}

// Shuffle array
function shuffleArray(array) {
    const shuffled = [...array];
    for (let i = shuffled.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
    }
    return shuffled;
}

// Export for Node.js if in server environment
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { gameData, shuffleArray };
}
