@echo off
cd images

:: Countries
echo ^<svg width="400" height="400" xmlns="http://www.w3.org/2000/svg"^>^<rect width="400" height="400" fill="#e74c3c"/^>^<text x="200" y="200" font-family="Arial" font-size="28" font-weight="bold" fill="white" text-anchor="middle" dominant-baseline="middle"^>Turkey^</text^>^</svg^> > countries\turkey.jpg
echo ^<svg width="400" height="400" xmlns="http://www.w3.org/2000/svg"^>^<rect width="400" height="400" fill="#3498db"/^>^<text x="200" y="200" font-family="Arial" font-size="28" font-weight="bold" fill="white" text-anchor="middle" dominant-baseline="middle"^>United States^</text^>^</svg^> > countries\usa.jpg
echo ^<svg width="400" height="400" xmlns="http://www.w3.org/2000/svg"^>^<rect width="400" height="400" fill="#f39c12"/^>^<text x="200" y="200" font-family="Arial" font-size="28" font-weight="bold" fill="white" text-anchor="middle" dominant-baseline="middle"^>Germany^</text^>^</svg^> > countries\germany.jpg
echo ^<svg width="400" height="400" xmlns="http://www.w3.org/2000/svg"^>^<rect width="400" height="400" fill="#9b59b6"/^>^<text x="200" y="200" font-family="Arial" font-size="28" font-weight="bold" fill="white" text-anchor="middle" dominant-baseline="middle"^>France^</text^>^</svg^> > countries\france.jpg
echo ^<svg width="400" height="400" xmlns="http://www.w3.org/2000/svg"^>^<rect width="400" height="400" fill="#2ecc71"/^>^<text x="200" y="200" font-family="Arial" font-size="28" font-weight="bold" fill="white" text-anchor="middle" dominant-baseline="middle"^>Italy^</text^>^</svg^> > countries\italy.jpg
echo ^<svg width="400" height="400" xmlns="http://www.w3.org/2000/svg"^>^<rect width="400" height="400" fill="#e67e22"/^>^<text x="200" y="200" font-family="Arial" font-size="28" font-weight="bold" fill="white" text-anchor="middle" dominant-baseline="middle"^>Spain^</text^>^</svg^> > countries\spain.jpg
echo ^<svg width="400" height="400" xmlns="http://www.w3.org/2000/svg"^>^<rect width="400" height="400" fill="#34495e"/^>^<text x="200" y="200" font-family="Arial" font-size="28" font-weight="bold" fill="white" text-anchor="middle" dominant-baseline="middle"^>United Kingdom^</text^>^</svg^> > countries\uk.jpg
echo ^<svg width="400" height="400" xmlns="http://www.w3.org/2000/svg"^>^<rect width="400" height="400" fill="#e91e63"/^>^<text x="200" y="200" font-family="Arial" font-size="28" font-weight="bold" fill="white" text-anchor="middle" dominant-baseline="middle"^>Japan^</text^>^</svg^> > countries\japan.jpg
echo ^<svg width="400" height="400" xmlns="http://www.w3.org/2000/svg"^>^<rect width="400" height="400" fill="#f1c40f"/^>^<text x="200" y="200" font-family="Arial" font-size="28" font-weight="bold" fill="white" text-anchor="middle" dominant-baseline="middle"^>Brazil^</text^>^</svg^> > countries\brazil.jpg
echo ^<svg width="400" height="400" xmlns="http://www.w3.org/2000/svg"^>^<rect width="400" height="400" fill="#95a5a6"/^>^<text x="200" y="200" font-family="Arial" font-size="28" font-weight="bold" fill="white" text-anchor="middle" dominant-baseline="middle"^>Canada^</text^>^</svg^> > countries\canada.jpg
echo ^<svg width="400" height="400" xmlns="http://www.w3.org/2000/svg"^>^<rect width="400" height="400" fill="#1abc9c"/^>^<text x="200" y="200" font-family="Arial" font-size="28" font-weight="bold" fill="white" text-anchor="middle" dominant-baseline="middle"^>Australia^</text^>^</svg^> > countries\australia.jpg
echo ^<svg width="400" height="400" xmlns="http://www.w3.org/2000/svg"^>^<rect width="400" height="400" fill="#ff7675"/^>^<text x="200" y="200" font-family="Arial" font-size="28" font-weight="bold" fill="white" text-anchor="middle" dominant-baseline="middle"^>Netherlands^</text^>^</svg^> > countries\netherlands.jpg

echo Created country placeholder images
