# Railway Deployment Configuration
# This file tells Railway how to deploy your application

[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
